### ISSUE TITLE
`pip install colout` is broken for everyone

### ISSUE THREAD

**Issue by tartley** [nojhan/colout#101]
`setup.py` tries to read 'README.md', but no such file exists in the source dist package on PyPI.

```
$ python3.7 -mpip install --user colout
Collecting colout
  Downloading https://files.pythonhosted.org/packages/3d/ba/3ef31c0df3ace69271cc8b1af6b529f24de66ff42c0d99a8d18aa980a307/colout-0.5.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 736kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gfp0x0mf/colout/setup.py", line 25, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gfp0x0mf/colout/
```

This is not limited to py3.7. Earlier versions fail in the same way.

**Comment by tartley** [comment]
Thank you SO MUCH for colout! I use it and love it every single day, and have done so for years.

I know it's hard maintaining old software. Would a PR help?

**Comment by tartley** [comment]
I see 'README.md' is mentioned in MANIFEST.in. Perhaps all that's needed is a new source release pushing up to PyPI?

**Comment by tartley** [comment]
LICENSE is also missing from PyPI, albeit mentioned in MANIFEST.in

**Comment by jquast** [comment]
I made PR #102 to suggest a small fix

**Comment by tartley** [comment]
@jquast  Nice work, especially the part where you ignored my foolish misdirection about the MANIFEST.in. :+1:

**Comment by jquast** [comment]
No problem :-) I just noticed we write similar libraries, 'blessed' and 'colorama', greetings!

**Comment by tartley** [comment]
Backatcha! Love Blessings so much. FWIW, I wish I'd never included the functionality in Colorama to generate ANSI codes. It's obviously way better to encourage people to use far superior stuff like blessings. Do one thing well. But i retired from the project (I don't use Windows any more) and backwards compatibility.

I created a humble thing using blessings. You must see far better things, but if you "pip install --user cbeams ; cbeams", it's kinda fun.

**Comment by raytry** [comment]
This method solved the problem for me:
`pip install --force-reinstall git+https://github.com/stdedos/colout.git`
Found this solution here: https://stackoverflow.com/questions/41695779/ioerror-errno-2-no-such-file-or-directory-readme-md#41695939

**Comment by tartley** [comment]
Worth noting that raytry's solution (which works for me) quotes a fork of the repo, not this (nojhan's) original. Should probably be:

    pip install --user --force-reinstall git+https://github.com/nojhan/colout.git

(I added a `--user` as well. So you can install tools like this globally without needing a virtualenv, without needing sudo, and without modifying your system wide installed libraries.)

**Comment by evandrocoan** [comment]
```
# pip3 install --force-reinstall git+https://github.com/nojhan/colout.git -v
Downloading/unpacking git+https://github.com/nojhan/colout.git
  Cloning https://github.com/nojhan/colout.git to /tmp/pip-ppgqwk0v-build
  Found command 'git' at '/usr/bin/git'
  Running setup.py (path:/tmp/pip-ppgqwk0v-build/setup.py) egg_info for package from git+https://github.com/nojhan/colout.git
    error in colout setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in colout setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-ppgqwk0v-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with
```

**Comment by evandrocoan** [comment]
I fixed by editing your `setup.py` and changing:
```py
requires = ['argparse; python_version < "2.7"', 'pygments', 'babel']
# -->
requires = ['argparse', 'pygments', 'babel']
```

**Comment by ferenczy** [comment]
It looks like this project is abandoned, I guess it's time for a fork, what do you think?

**Comment by tartley** [comment]
>  time for a fork

Without the involvement and blessing of colout's author(s), I fear that's easily perceived as hostile, and I'd much rather try to be helpful to convey my massive gratitude.

It is frustrating though, that the fixes required to make this work have been merged for more than a year, but without a release, the package is still uninstallable from PyPI.

To be explicit: Of the README's listed install methods:

* "setup.py install" does work, but it requires cloning the repo, then further fiddly manual steps.
* "pip install colout" doesn't work for anyone, because of the reasons above.
* "easy_install colout" doesn't work for anyone, for the same reasons.
* apt install from PPA doesn't support the current Ubunut (19.04)

Perhaps it would help to add a sanity test that builds & installs an sdist or wheel, thus revealing future breakage at test time, before problems get merged?

@nojhan I'd love to help out! Are you seeing this? :-) Could you make a PyPI release, which would, I believe, fix all this?

**Comment by tartley** [comment]
@ferenczy Be aware, there is an existing fork with some newer commits, here: https://github.com/stdedos/colout

Doesn't solve the problem of how to make a new PyPI release (without which, their install instructions don't work either) but maybe they could adopt a new PyPI package name, "neocolout" or something)

**Comment by jdevera** [comment]
@nojhan is this project abandoned?

**Comment by tartley** [comment]
Closed since 'colout' gained working PyPI releases aaaaaaages ago now. Thank you!

**Comment by nojhan** [comment]
I have to confess I had a few bad years and did not follow this thread. Is there anything that need to be done on having an up-to-date pypi package?

**Comment by tartley** [comment]
No worries at all, I have open source packages of my own that have languished when times were tough, so I totally understand.

I think pip installs are 100% working fine as well, so you can forget all about this issue. Go! Have some fun! Get some rest! Everybody loves you.

**Comment by nojhan** [comment]
Man, this is the weirdest, yet kindest comment I've seen in a while :rofl:
